export interface Peak {
  name: string;
  state: string;
  elevation: number; // in meters
}

export const US_STATE_HIGHPOINTS: Peak[] = [
  { name: 'Britton Hill', state: 'Florida', elevation: 105 },
  { name: 'Ebright Azimuth', state: 'Delaware', elevation: 137 },
  { name: 'Driskill Mountain', state: 'Louisiana', elevation: 163 },
  { name: 'Woodall Mountain', state: 'Mississippi', elevation: 246 },
  { name: 'Jerimoth Hill', state: 'Rhode Island', elevation: 247 },
  { name: 'Hoosier Hill', state: 'Indiana', elevation: 383 },
  { name: 'Charles Mound', state: 'Illinois', elevation: 376 },
  { name: 'Campbell Hill', state: 'Ohio', elevation: 472 },
  { name: 'Hawkeye Point', state: 'Iowa', elevation: 509 },
  { name: 'Taum Sauk Mountain', state: 'Missouri', elevation: 540 },
  { name: 'Mount Arvon', state: 'Michigan', elevation: 603 },
  { name: 'Timms Hill', state: 'Wisconsin', elevation: 595 },
  { name: 'Eagle Mountain', state: 'Minnesota', elevation: 701 },
  { name: 'Mount Frissell', state: 'Connecticut', elevation: 725 },
  { name: 'Cheaha Mountain', state: 'Alabama', elevation: 735 },
  { name: 'High Point', state: 'New Jersey', elevation: 550 },
  { name: 'Mount Davis', state: 'Pennsylvania', elevation: 979 },
  { name: 'Hoye-Crest', state: 'Maryland', elevation: 1024 },
  { name: 'Sassafras Mountain', state: 'South Carolina', elevation: 1085 },
  { name: 'Black Mountain', state: 'Kentucky', elevation: 1263 },
  { name: 'Brasstown Bald', state: 'Georgia', elevation: 1458 },
  { name: 'Spruce Knob', state: 'West Virginia', elevation: 1482 },
  { name: 'Mount Greylock', state: 'Massachusetts', elevation: 1064 },
  { name: 'Mount Washington', state: 'New Hampshire', elevation: 1917 },
  { name: 'Mount Katahdin', state: 'Maine', elevation: 1606 },
  { name: 'Mount Mansfield', state: 'Vermont', elevation: 1339 },
  { name: 'Mount Marcy', state: 'New York', elevation: 1629 },
  { name: 'Clingmans Dome', state: 'Tennessee', elevation: 2025 },
  { name: 'Mount Mitchell', state: 'North Carolina', elevation: 2037 },
  { name: 'Mount Rogers', state: 'Virginia', elevation: 1746 },
  { name: 'White Butte', state: 'North Dakota', elevation: 1069 },
  { name: 'Black Elk Peak', state: 'South Dakota', elevation: 2207 },
  { name: 'Panorama Point', state: 'Nebraska', elevation: 1653 },
  { name: 'Mount Sunflower', state: 'Kansas', elevation: 1231 },
  { name: 'Black Mesa', state: 'Oklahoma', elevation: 1516 },
  { name: 'Guadalupe Peak', state: 'Texas', elevation: 2667 },
  { name: 'Humphreys Peak', state: 'Arizona', elevation: 3851 },
  { name: 'Wheeler Peak', state: 'New Mexico', elevation: 4013 },
  { name: 'Mount Elbert', state: 'Colorado', elevation: 4401 },
  { name: 'Gannett Peak', state: 'Wyoming', elevation: 4209 },
  { name: 'Kings Peak', state: 'Utah', elevation: 4125 },
  { name: 'Boundary Peak', state: 'Nevada', elevation: 4007 },
  { name: 'Granite Peak', state: 'Montana', elevation: 3901 },
  { name: 'Borah Peak', state: 'Idaho', elevation: 3859 },
  { name: 'Mount Rainier', state: 'Washington', elevation: 4392 },
  { name: 'Mount Hood', state: 'Oregon', elevation: 3429 },
  { name: 'Mount Whitney', state: 'California', elevation: 4421 },
  { name: 'Mauna Kea', state: 'Hawaii', elevation: 4207 },
  { name: 'Denali', state: 'Alaska', elevation: 6190 },
];
